// <auto-generated />
using System;
using DunFlow.Infra.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DunFlow.Infra.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260316172301_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DunFlow.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Nadav"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Nashef"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Dun"
                        });
                });

            modelBuilder.Entity("DunFlow.Domain.Entities.FormField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ControlType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WorkTaskStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkTaskStatusId");

                    b.ToTable("FormFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ControlType = "textarea",
                            IsRequired = true,
                            Key = "SpecificationText",
                            Label = "Specification Details",
                            WorkTaskStatusId = 2
                        },
                        new
                        {
                            Id = 2,
                            ControlType = "text",
                            IsRequired = true,
                            Key = "BranchName",
                            Label = "Branch Name",
                            WorkTaskStatusId = 3
                        },
                        new
                        {
                            Id = 3,
                            ControlType = "text",
                            IsRequired = true,
                            Key = "VersionNumber",
                            Label = "Release Version",
                            WorkTaskStatusId = 4
                        },
                        new
                        {
                            Id = 4,
                            ControlType = "text",
                            IsRequired = true,
                            Key = "SupplierName",
                            Label = "Supplier Name",
                            WorkTaskStatusId = 6
                        },
                        new
                        {
                            Id = 5,
                            ControlType = "number",
                            IsRequired = true,
                            Key = "Amount",
                            Label = "Amount",
                            WorkTaskStatusId = 6
                        },
                        new
                        {
                            Id = 6,
                            ControlType = "text",
                            IsRequired = true,
                            Key = "ApprovedBy",
                            Label = "Approved By",
                            WorkTaskStatusId = 7
                        },
                        new
                        {
                            Id = 7,
                            ControlType = "text",
                            IsRequired = true,
                            Key = "OrderId",
                            Label = "Order ID",
                            WorkTaskStatusId = 7
                        },
                        new
                        {
                            Id = 8,
                            ControlType = "url",
                            IsRequired = true,
                            Key = "ReceiptImageLink",
                            Label = "Receipt Image Link",
                            WorkTaskStatusId = 8
                        });
                });

            modelBuilder.Entity("DunFlow.Domain.Entities.WorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkTaskTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("WorkTaskTypeId");

                    b.ToTable("WorkTasks", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("WorkTasksHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DunFlow.Domain.Entities.WorkTaskStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<int>("StatusValue")
                        .HasColumnType("int");

                    b.Property<int>("WorkTaskTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkTaskTypeId");

                    b.ToTable("WorkTaskStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Created",
                            IsFinal = false,
                            StatusValue = 1,
                            WorkTaskTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Specification Completed",
                            IsFinal = false,
                            StatusValue = 2,
                            WorkTaskTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Development Completed",
                            IsFinal = false,
                            StatusValue = 3,
                            WorkTaskTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Distribution Completed",
                            IsFinal = true,
                            StatusValue = 4,
                            WorkTaskTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Created",
                            IsFinal = false,
                            StatusValue = 1,
                            WorkTaskTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "Supplier Offers Received",
                            IsFinal = false,
                            StatusValue = 2,
                            WorkTaskTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            DisplayName = "Purchasing Approval",
                            IsFinal = false,
                            StatusValue = 3,
                            WorkTaskTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            DisplayName = "Receipt Image Upload",
                            IsFinal = true,
                            StatusValue = 4,
                            WorkTaskTypeId = 2
                        });
                });

            modelBuilder.Entity("DunFlow.Domain.Entities.WorkTaskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("WorkTaskTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Software Development Task",
                            Name = "Development"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Purchasing and Procurement",
                            Name = "Procurement"
                        });
                });

            modelBuilder.Entity("DunFlow.Domain.Entities.FormField", b =>
                {
                    b.HasOne("DunFlow.Domain.Entities.WorkTaskStatus", "WorkTaskStatus")
                        .WithMany("FormFields")
                        .HasForeignKey("WorkTaskStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkTaskStatus");
                });

            modelBuilder.Entity("DunFlow.Domain.Entities.WorkTask", b =>
                {
                    b.HasOne("DunFlow.Domain.Entities.AppUser", "AssignedUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DunFlow.Domain.Entities.WorkTaskType", "WorkTaskType")
                        .WithMany("WorkTasks")
                        .HasForeignKey("WorkTaskTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("WorkTaskType");
                });

            modelBuilder.Entity("DunFlow.Domain.Entities.WorkTaskStatus", b =>
                {
                    b.HasOne("DunFlow.Domain.Entities.WorkTaskType", "WorkTaskType")
                        .WithMany("Statuses")
                        .HasForeignKey("WorkTaskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkTaskType");
                });

            modelBuilder.Entity("DunFlow.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("AssignedTasks");
                });

            modelBuilder.Entity("DunFlow.Domain.Entities.WorkTaskStatus", b =>
                {
                    b.Navigation("FormFields");
                });

            modelBuilder.Entity("DunFlow.Domain.Entities.WorkTaskType", b =>
                {
                    b.Navigation("Statuses");

                    b.Navigation("WorkTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
